import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from '@/components/shared/sidebar';
import Header from '@/components/shared/header'; // 1. Importa el Header
import { Toaster } from 'react-hot-toast';

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "el sijan",
  description: "Generated by create next app en next 13 con NestJS y TypeORM",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex antialiased bg-[#DBDACE]">
        <Toaster position="top-right" />
        
        {/* Sidebar fija a la izquierda */}
        <Sidebar />

        {/* Contenedor principal */}
        <div className="flex-1 flex flex-col min-h-screen">
          {/* 2. Insertamos el Header aquí arriba */}
          <Header /> 

          {/* 3. El contenido de las páginas debajo del Header */}
          <main className="flex-1 p-8 transition-all duration-300">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}