import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from 'react-hot-toast';
import MainLayoutWrapper from "./MainLayoutWrapper"; // El archivo que crearemos

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

// ✅ Aquí mantenemos tu título intacto
export const metadata: Metadata = {
  title: "el sijan",
  description: "Generated by create next app en next 13 con NestJS y TypeORM",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es" className="h-full">
      <body className={`${geistSans.variable} ${geistMono.variable} min-h-screen flex bg-gray-50 text-gray-900 antialiased`}>
        <Toaster position="top-right" />
        
        {/* Pasamos toda la lógica al envoltorio de cliente */}
        <MainLayoutWrapper>
          {children}
        </MainLayoutWrapper>
      </body>
    </html>
  );
}